### ISSUE TITLE
catkin build failed for tello_catkin_ws

### ISSUE THREAD

**Issue by washichi** [tau-adl/Tello_ROS_ORBSLAM#1]
building tello_catkin_ws on ubuntu 16.04 + ROS kinetic results in 4/7 succeeded. 
(using CmakeLists.txt for kinetic)

I get the following error:

```
CMake Error at /home/uburos/ROS/Tello_ROS_ORBSLAM/ROS/tello_catkin_ws/src/orb_slam_2_ros/CMakeLists.txt:175 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "orb_slam2_ros_mono".


CMake Error at /home/uburos/ROS/Tello_ROS_ORBSLAM/ROS/tello_catkin_ws/src/orb_slam_2_ros/CMakeLists.txt:181 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "orb_slam2_ros".
```
it goes wrong in CmakeLists.txt line 173:
https://github.com/tau-adl/Tello_ROS_ORBSLAM/blob/411a4e11a44b2b5bf34ad8146bae7c72179003d8/ROS/tello_catkin_ws/src/orb_slam_2_ros/CMakeLists.txt#L173

looks like CATKIN_PACKAGE_LIB_DESTINATION doesn't point to anything.
I tried replacing it with " /lib"  but then I get other errors (ros/ros.h unknown)

I don't know enough about cmake to fix this, is something wrong with my catkin or is this an issue with the cmakelists file? 

[build.cmake.000.log](https://github.com/tau-adl/Tello_ROS_ORBSLAM/files/4423276/build.cmake.000.log)

**Comment by ArkadyZis** [comment]
Hello, please try to use CmakeFile_changed2 instead.

**Comment by washichi** [comment]
Thank you, It builds successfully now. 
my system would freeze during build (94%) but `catkin build --mem-limit 70% -j1` worked for me.
